In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
euclid_duos=[['Yersinia pestis', 'Yersinia pseudotuberculosis'],
['Bacillus anthracis', 'Bacillus cereus'],
['Proteus vulgaris', 'Pseudomonas aeruginosa'],
['Streptococcus sanguinis', 'Yersinia enterocolitica'],
['Proteus mirabilis', 'Proteus vulgaris'],
['Bordetella parapertussis', 'Bordetella pertussis'],
['Staphylococcus epidermidis', 'Staphylococcus lugdunensis'],
['Staphylococcus lugdunensis', 'Staphylococcus saprophyticus'],
['Mycobacterium gordonae', 'Mycobacterium kansasii'],
['Yersinia enterocolitica', 'Yersinia pestis'],
['Micrococcus luteus', 'Mycobacterium fortuitum'],
['Staphylococcus aureus', 'Staphylococcus epidermidis'],
['Yersinia enterocolitica', 'Yersinia pseudotuberculosis'],
['Proteus mirabilis', 'Pseudomonas aeruginosa'],
['Acinetobacter calcoaceticus', 'Aerococcus viridans'],
['Streptococcus sanguinis', 'Yersinia pestis'],
['Staphylococcus aureus', 'Staphylococcus lugdunensis'],
['Treponema pallidum', 'Yersinia enterocolitica'],
['Treponema pallidum', 'Streptococcus sanguinis'],
['Streptococcus agalactiae', 'Streptococcus pyogenes'],
['Streptococcus sanguinis', 'Yersinia pseudotuberculosis'],
['Mycobacterium fortuitum', 'Mycobacterium gordonae'],
['Staphylococcus epidermidis', 'Staphylococcus saprophyticus'],
['Enterococcus faecium', 'Enterococcus gallinarum'],
['Salmonella enterica', 'Serratia marcescens'],
['Acinetobacter baumannii', 'Aerococcus viridans'],
['Staphylococcus saprophyticus', 'Streptococcus pyogenes'],
['Treponema pallidum', 'Yersinia pestis'],
['Staphylococcus lugdunensis', 'Streptococcus agalactiae'],
['Streptococcus pneumoniae', 'Streptococcus pyogenes'],
['Oligella urethralis', 'Pasteurella multocida'],
['Staphylococcus epidermidis', 'Streptococcus agalactiae'],
['Staphylococcus saprophyticus', 'Streptococcus agalactiae'],
['Staphylococcus lugdunensis', 'Streptococcus pneumoniae'],
['Staphylococcus lugdunensis', 'Streptococcus pyogenes'],
['Neisseria meningitidis', 'Oligella urethralis'],
['Staphylococcus aureus', 'Staphylococcus saprophyticus'],
['Treponema pallidum', 'Yersinia pseudotuberculosis'],
['Bordetella pertussis', 'Citrobacter freundii'],
['Streptococcus agalactiae', 'Streptococcus pneumoniae'],
['Staphylococcus epidermidis', 'Streptococcus pneumoniae'],
['Staphylococcus saprophyticus', 'Streptococcus pneumoniae'],
['Escherichia coli', 'Klebsiella pneumoniae'],
['Enterococcus faecalis', 'Escherichia coli'],
['Enterococcus faecalis', 'Enterococcus gallinarum'],
['Clostridium difficile', 'Clostridium perfringens'],
['Micrococcus luteus', 'Mycobacterium gordonae'],
['Mycobacterium fortuitum', 'Mycobacterium kansasii'],
['Acinetobacter calcoaceticus', 'Acinetobacter baumannii'],
['Bordetella parapertussis', 'Citrobacter freundii']]

In [9]:
from Bio import SeqIO
aligned_list = []
names = []
for seq_record in SeqIO.parse("out58_nospaces_beta.fasta", "fasta"):
    aligned_list.append(seq_record.seq)
    names.append(" ".join(seq_record.name.split('_')))
names = np.asarray(names)
names[names=='Clostridioides difficile'] = 'Clostridium difficile'
names[names=='Corynebacterium sp.'] = 'Corynebacterium'
names[names=='Mycolicibacterium fortuitum'] = 'Mycobacterium fortuitum'
names[names=='Cutibacterium acnes'] = 'Propionibacterium acnes'

In [10]:
from dtaidistance import dtw
from Bio import pairwise2

df_58_norm_shifted = pd.read_csv('df_58_norm_shifted.csv', index_col=0)

table1 = pd.DataFrame()
table1['Pair'] = range(1,16)
table1['Organism 1'] = [i[0] for i in euclid_duos[:15]]
table1['Organism 2'] = [i[1] for i in euclid_duos[:15]]
table1['ED'] = np.round(pd.read_csv('distances_euc.csv').iloc[:,1].values[:15],2)
table1['ID'] = [round(100*(1-(max([len(aligned_list[np.where(names==duo[0])[0][0]]),len(aligned_list[np.where(names==duo[1])[0][0]])])-
 pairwise2.align.localxx(aligned_list[np.where(names==duo[0])[0][0]], aligned_list[np.where(names==duo[1])[0][0]], score_only=True))/max([len(aligned_list[np.where(names==duo[0])[0][0]]),len(aligned_list[np.where(names==duo[1])[0][0]])])),2) for duo in euclid_duos[:15]]
table1['Mismatches'] = [int(max([len(aligned_list[np.where(names==duo[0])[0][0]]),len(aligned_list[np.where(names==duo[1])[0][0]])])-
 pairwise2.align.localxx(aligned_list[np.where(names==duo[0])[0][0]], aligned_list[np.where(names==duo[1])[0][0]], score_only=True)) for duo in euclid_duos[:15]]
# table1['DTW w=1'] = [dtw.distance(df_58_norm_shifted.loc[duo[0]].values, df_58_norm_shifted.loc[duo[1]].values, window=1) for duo in euclid_duos[:15]]
# table1['DTW w=2'] = [dtw.distance(df_58_norm_shifted.loc[duo[0]].values, df_58_norm_shifted.loc[duo[1]].values, window=2) for duo in euclid_duos[:15]]
# table1['DTW w=3'] = [dtw.distance(df_58_norm_shifted.loc[duo[0]].values, df_58_norm_shifted.loc[duo[1]].values, window=3) for duo in euclid_duos[:15]]
table1['DTW'] = [np.round(dtw.distance(df_58_norm_shifted.loc[duo[0]].values, df_58_norm_shifted.loc[duo[1]].values),2) for duo in euclid_duos[:15]]
table1['Sorted by DTW'] = table1['DTW'].sort_values().index.values+1
table1

,Pair,Organism 1,Organism 2,ED,ID,Mismatches,DTW,Sorted by DTW
0,1,Yersinia pestis,Yersinia pseudotuberculosis,1.10,99.79,2,0.40,2
1,2,Bacillus anthracis,Bacillus cereus,1.11,99.69,3,0.24,1
2,3,Proteus vulgaris,Pseudomonas aeruginosa,1.55,87.62,120,0.60,15
3,4,Streptococcus sanguinis,Yersinia enterocolitica,1.66,84.74,148,0.61,3
4,5,Proteus mirabilis,Proteus vulgaris,1.76,98.56,14,0.77,4
5,6,Bordetella parapertussis,Bordetella pertussis,1.86,99.90,1,0.75,11
6,7,Staphylococcus epidermidis,Staphylococcus lugdunensis,1.93,98.27,17,0.62,7
7,8,Staphylococcus lugdunensis,Staphylococcus saprophyticus,2.00,98.37,16,1.43,14
8,9,Mycobacterium gordonae,Mycobacterium kansasii,2.03,98.34,16,0.71,9
9,10,Yersinia enterocolitica,Yersinia pestis,2.16,96.70,32,0.79,12
10,11,Micrococcus luteus,Mycobacterium fortuitum,2.25,90.87,87,0.61,6
11,12,Staphylococcus aureus,Staphylococcus epidermidis,2.32,98.57,14,0.74,5
12,13,Yersinia enterocolitica,Yersinia pseudotuberculosis,2.52,96.49,34,0.78,13
13,14,Proteus mirabilis,Pseudomonas aeruginosa,2.71,87.82,118,0.65,10
14,15,Acinetobacter calcoaceticus,Aerococcus viridans,2.82,81.31,183,0.50,8

In [11]:
print(table1.to_latex())

\begin{tabular}{lrllrrrrr}
\toprule
{} &  Pair &                   Organism 1 &                    Organism 2 &    ED &     ID &  Mismatches &   DTW &  Sorted by DTW \\
\midrule
0  &     1 &              Yersinia pestis &   Yersinia pseudotuberculosis &  1.10 &  99.79 &           2 &  0.40 &              2 \\
1  &     2 &           Bacillus anthracis &               Bacillus cereus &  1.11 &  99.69 &           3 &  0.24 &              1 \\
2  &     3 &             Proteus vulgaris &        Pseudomonas aeruginosa &  1.55 &  87.62 &         120 &  0.60 &             15 \\
3  &     4 &      Streptococcus sanguinis &       Yersinia enterocolitica &  1.66 &  84.74 &         148 &  0.61 &              3 \\
4  &     5 &            Proteus mirabilis &              Proteus vulgaris &  1.76 &  98.56 &          14 &  0.77 &              4 \\
5  &     6 &     Bordetella parapertussis &          Bordetella pertussis &  1.86 &  99.90 &           1 &  0.75 &             11 \\
6  &     7 &   Staphylococcus epidermidis &    Staphylococcus lugdunensis &  1.93 &  98.27 &          17 &  0.62 &              7 \\
7  &     8 &   Staphylococcus lugdunensis &  Staphylococcus saprophyticus &  2.00 &  98.37 &          16 &  1.43 &             14 \\
8  &     9 &       Mycobacterium gordonae &        Mycobacterium kansasii &  2.03 &  98.34 &          16 &  0.71 &              9 \\
9  &    10 &      Yersinia enterocolitica &               Yersinia pestis &  2.16 &  96.70 &          32 &  0.79 &             12 \\
10 &    11 &           Micrococcus luteus &       Mycobacterium fortuitum &  2.25 &  90.87 &          87 &  0.61 &              6 \\
11 &    12 &        Staphylococcus aureus &    Staphylococcus epidermidis &  2.32 &  98.57 &          14 &  0.74 &              5 \\
12 &    13 &      Yersinia enterocolitica &   Yersinia pseudotuberculosis &  2.52 &  96.49 &          34 &  0.78 &             13 \\
13 &    14 &            Proteus mirabilis &        Pseudomonas aeruginosa &  2.71 &  87.82 &         118 &  0.65 &             10 \\
14 &    15 &  Acinetobacter calcoaceticus &           Aerococcus viridans &  2.82 &  81.31 &         183 &  0.50 &              8 \\
\bottomrule
\end{tabular}

# Table 1

In [5]:
from Bio import SeqIO
aligned_list = []
names = []
for seq_record in SeqIO.parse("Import Files/out10_nospaces.fasta", "fasta"):
    aligned_list.append(seq_record.seq)
    print(" ".join(seq_record.name.split('_')),len(seq_record.seq))

Citrobacterkoseri 969
Enterococcusfaecium 978
Escherichiacoli 981
Streptococcussp. 978
Haemophilusinfluenzae 967
Listeriamonocytogenes 994
Staphylococcusaureus 981
Streptococcusgallolyticus 978
Streptococcuspneumoniae 978
Streptococcussanguinis 972